"""
Configuration: analysis parameters and Libertex -> yfinance symbol mapping.
"""

# === Analysis Parameters ===
LOOKBACK_DAYS = 365      # Days of historical data to fetch
SHORT_MA_PERIOD = 20     # Short EMA period
MEDIUM_MA_PERIOD = 50    # Medium SMA period
LONG_MA_PERIOD = 200     # Long SMA period
SIGNAL_WINDOW = 5        # Days to look back for a recent break signal
DONCHIAN_PERIOD = 20     # Period for Donchian channel breakout check
FETCH_WORKERS = 10       # Parallel download threads

# === yfinance Symbol Mapping ===
# Maps Libertex symbols -> yfinance tickers
SYMBOL_MAP: dict[str, str] = {
    # ── Commodities ──────────────────────────────────────────────────────────
    "BRN":          "BZ=F",      # Brent Crude Oil
    "CL":           "CL=F",      # Light Sweet Crude Oil (WTI front-month)
    "COCOA":        "CC=F",      # Cocoa
    "COFFEE":       "KC=F",      # Coffee C
    "CORN":         "ZC=F",      # Corn
    "COTTON":       "CT=F",      # Cotton #2
    "HG":           "HG=F",      # Copper
    "HO":           "HO=F",      # Heating Oil
    "LHOGS":        "HE=F",      # Lean Hogs
    "LTCATTLE":     "LE=F",      # Live Cattle
    "NG":           "NG=F",      # Henry Hub Natural Gas
    "OJ":           "OJ=F",      # Orange Juice
    "PA":           "PA=F",      # Palladium
    "PL":           "PL=F",      # Platinum
    "RBOB":         "RB=F",      # RBOB Gasoline
    "SOYBEAN":      "ZS=F",      # Soybean
    "SUGAR":        "SB=F",      # Sugar #11
    "WHEAT":        "ZW=F",      # Wheat
    "WT":           "CL=F",      # WTI Crude (same futures contract as CL)
    "XAGUSD":       "SI=F",      # Silver
    "XAUUSD":       "GC=F",      # Gold

    # ── US / ADR stocks ───────────────────────────────────────────────────────
    "AA":           "AA",
    "AAPL":         "AAPL",
    "ABEV":         "ABEV",
    "ACB":          "ACB",
    "ADBE":         "ADBE",
    "AMC":          "AMC",
    "AMD":          "AMD",
    "AMZN":         "AMZN",
    "ATVI":         "ATVI",
    "AXP":          "AXP",
    "BA":           "BA",
    "BABA":         "BABA",
    "BAC":          "BAC",
    "BIDU":         "BIDU",
    "BNPQY":        "BNPQY",
    "BSAC":         "BSAC",
    "C":            "C",
    "CAT":          "CAT",
    "CCL":          "CCL",
    "COIN":         "COIN",
    "CRM":          "CRM",
    "CRON":         "CRON",
    "CSCO":         "CSCO",
    "DIS":          "DIS",
    "Dropbox":      "DBX",
    "EBAY":         "EBAY",
    "EL":           "EL",
    "ENIC":         "ENIC",
    "ETH":          "ETH",       # Ethan Allen (NOT crypto)
    "F":            "F",
    "FB":           "META",      # Facebook → Meta
    "FCX":          "FCX",
    "GBTC":         "GBTC",
    "GE":           "GE",
    "GILD":         "GILD",
    "GME":          "GME",
    "GOOGL":        "GOOGL",
    "GS":           "GS",
    "HD":           "HD",
    "HOG":          "HOG",
    "HOOD":         "HOOD",
    "HPQ":          "HPQ",
    "IBM":          "IBM",
    "INTC":         "INTC",
    "JNJ":          "JNJ",
    "JPM":          "JPM",
    "JWN":          "JWN",
    "KO":           "KO",
    "KORS":         "CPRI",      # Michael Kors → Capri Holdings
    "LUV":          "LUV",
    "LYFT":         "LYFT",
    "MA":           "MA",
    "MARA":         "MARA",
    "MCD":          "MCD",
    "MRNA":         "MRNA",
    "MSFT":         "MSFT",
    "MU":           "MU",
    "NCLH":         "NCLH",
    "NINTENDO_US":  "NTDOY",
    "NKE":          "NKE",
    "NVDA":         "NVDA",
    "Netflix":      "NFLX",
    "ORCL":         "ORCL",
    "PBR":          "PBR",
    "PFE":          "PFE",
    "PG":           "PG",
    "PINS":         "PINS",
    "PM":           "PM",
    "PVH":          "PVH",
    "RACE":         "RACE",
    "RCL":          "RCL",
    "RL":           "RL",
    "RNLSY":        "RNLSY",
    "RYAAY":        "RYAAY",
    "SAP":          "SAP",
    "SAVE":         "SAVE",
    "SBUX":         "SBUX",
    "SIRI":         "SIRI",
    "SNAP":         "SNAP",
    "SPCE":         "SPCE",
    "SQM":          "SQM",
    "SVMK":         "MNTV",      # SurveyMonkey → Momentive
    "Spotify":      "SPOT",
    "T":            "T",
    "TLRY":         "TLRY",
    "TM":           "TM",
    "TRIP":         "TRIP",
    "TRV":          "TRV",
    "TSLA":         "TSLA",
    "UBER":         "UBER",
    "UNH":          "UNH",
    "V":            "V",
    "VALE":         "VALE",
    "VFC":          "VFC",
    "VZ":           "VZ",
    "WEED":         "CGC",       # Canopy Growth (US listing)
    "WFC":          "WFC",
    "WSM":          "WSM",
    "WYNN":         "WYNN",
    "XOM":          "XOM",

    # ── European stocks (exchange suffix) ─────────────────────────────────────
    "ADS":          "ADS.DE",    # Adidas
    "AIR":          "AIR.PA",    # Airbus
    "AIRF":         "AF.PA",     # Air France-KLM
    "BAS":          "BAS.DE",    # BASF
    "BAYN":         "BAYN.DE",   # Bayer
    "BMW":          "BMW.DE",
    "DAI":          "MBG.DE",    # Mercedes-Benz (formerly Daimler)
    "DBK":          "DBK.DE",    # Deutsche Bank
    "DG":           "DG.PA",     # Vinci SA
    "ENEL":         "ENEL.MI",   # Enel SpA
    "ENI":          "ENI.MI",    # Eni SpA
    "FP":           "TTE.PA",    # TotalEnergies
    "ITX":          "ITX.MC",    # Inditex
    "REP":          "REP.MC",    # Repsol
    "SIE":          "SIE.DE",    # Siemens
    "TUI":          "TUI1.DE",
    "VOW":          "VOW3.DE",   # Volkswagen ordinary shares

    # ── Asian stocks ──────────────────────────────────────────────────────────
    "IDCB":         "1398.HK",   # ICBC
    "LNVG":         "0992.HK",   # Lenovo
    "NINTENDO_JP":  "7974.T",    # Nintendo (Tokyo)
    "TCTZ":         "0700.HK",   # Tencent
}

# === Sector Mapping ===
# Maps Libertex/yfinance symbol -> sector label
# Sectors: Technology, Finance, Automobile, Industrial, Telecommunication,
#          Energy, Materials, Healthcare, Consumer Services, Consumer Goods, Luxury
SECTOR_MAP: dict[str, str] = {
    # ── Commodities ───────────────────────────────────────────────────────────
    "BRN":      "Commodities — Energy",
    "CL":       "Commodities — Energy",
    "HO":       "Commodities — Energy",
    "NG":       "Commodities — Energy",
    "RBOB":     "Commodities — Energy",
    "WT":       "Commodities — Energy",
    "XAUUSD":   "Commodities — Metals",
    "XAGUSD":   "Commodities — Metals",
    "HG":       "Commodities — Metals",
    "PA":       "Commodities — Metals",
    "PL":       "Commodities — Metals",
    "COCOA":    "Commodities — Softs",
    "COFFEE":   "Commodities — Softs",
    "COTTON":   "Commodities — Softs",
    "OJ":       "Commodities — Softs",
    "SUGAR":    "Commodities — Softs",
    "CORN":     "Commodities — Grains",
    "SOYBEAN":  "Commodities — Grains",
    "WHEAT":    "Commodities — Grains",
    "LHOGS":    "Commodities — Livestock",
    "LTCATTLE": "Commodities — Livestock",
    # ── Technology ────────────────────────────────────────────────────────────
    "A":      "Technology",   # Agilent Technologies
    "AAPL":   "Technology",
    "ACAD":   "Healthcare",
    "ACIW":   "Technology",   # ACI Worldwide
    "ACN":    "Technology",   # Accenture
    "ADBE":   "Technology",
    "ADI":    "Technology",   # Analog Devices
    "ADP":    "Technology",
    "ADPT":   "Technology",   # Adaptive Biotechnologies
    "ADSK":   "Technology",
    "AEIS":   "Technology",   # Advanced Energy
    "AI":     "Technology",   # C3.ai
    "AKAM":   "Technology",
    "ALAB":   "Technology",   # Astera Labs
    "ALGN":   "Healthcare",
    "ALKS":   "Healthcare",
    "ALNY":   "Healthcare",
    "AMAT":   "Technology",
    "AMBA":   "Technology",
    "AMD":    "Technology",
    "ANET":   "Technology",
    "APH":    "Technology",   # Amphenol
    "APPN":   "Technology",   # Appian
    "ARCC":   "Finance",
    "ARES":   "Finance",
    "ARGX":   "Healthcare",
    "ARM":    "Technology",
    "ARWR":   "Healthcare",
    "ASAN":   "Technology",
    "ASML":   "Technology",
    "ASTS":   "Telecommunication",
    "AVAV":   "Industrial",   # AeroVironment
    "AVGO":   "Technology",
    "AXON":   "Technology",   # Axon Enterprise
    "AXP":    "Finance",
    "AZN":    "Healthcare",
    "AZO":    "Consumer Services",
    "BABA":   "Technology",   # Alibaba
    "BAC":    "Finance",
    "BB":     "Technology",   # BlackBerry
    "BBIO":   "Healthcare",
    "BBVA":   "Finance",
    "BBY":    "Consumer Services", # Best Buy
    "BCE":    "Telecommunication",
    "BCS":    "Finance",
    "BDX":    "Healthcare",
    "BIDU":   "Technology",
    "BIIB":   "Healthcare",
    "BILI":   "Technology",   # Bilibili
    "BIO":    "Healthcare",
    "BK":     "Finance",
    "BKNG":   "Consumer Services",
    "BKR":    "Energy",
    "BLK":    "Finance",
    "BLKB":   "Technology",   # Blackbaud
    "BMBL":   "Technology",   # Bumble
    "BMY":    "Healthcare",
    "BNTX":   "Healthcare",
    "BR":     "Technology",   # Broadridge
    "BRKR":   "Healthcare",
    "BSX":    "Healthcare",
    "BSY":    "Technology",   # Bentley Systems
    "BTI":    "Consumer Goods",
    "BX":     "Finance",
    "C":      "Finance",      # Citigroup
    "CACI":   "Technology",
    "CAT":    "Industrial",
    "CB":     "Finance",
    "CBRE":   "Finance",
    "CDNS":   "Technology",
    "CDW":    "Technology",
    "CEG":    "Energy",       # Constellation Energy
    "CELH":   "Consumer Goods",
    "CF":     "Materials",
    "CFG":    "Finance",
    "CG":     "Finance",
    "CHKP":   "Technology",
    "CHTR":   "Telecommunication",
    "CI":     "Healthcare",
    "CIEN":   "Technology",
    "CINF":   "Finance",
    "CLF":    "Materials",
    "CLH":    "Industrial",
    "CLS":    "Technology",   # Celestica
    "CLSK":   "Technology",   # CleanSpark (crypto mining)
    "CLX":    "Consumer Goods",
    "CM":     "Finance",
    "CMCSA":  "Telecommunication",
    "CME":    "Finance",
    "CMI":    "Industrial",
    "CNC":    "Healthcare",
    "CNI":    "Industrial",
    "CNP":    "Energy",
    "CNQ":    "Energy",
    "COF":    "Finance",
    "COHR":   "Technology",
    "COIN":   "Finance",
    "COP":    "Energy",
    "COST":   "Consumer Services",
    "CP":     "Industrial",
    "CPAY":   "Technology",   # Corpay
    "CPNG":   "Consumer Services",
    "CPRI":   "Luxury",       # Capri (Versace, Michael Kors, Jimmy Choo)
    "CPRT":   "Consumer Services",
    "CRM":    "Technology",
    "CRON":   "Consumer Goods",
    "CRWD":   "Technology",
    "CSCO":   "Technology",
    "CSGP":   "Technology",   # CoStar Group
    "CSX":    "Industrial",
    "CTAS":   "Industrial",
    "CTSH":   "Technology",
    "CTVA":   "Materials",
    "CVS":    "Healthcare",
    "CVNA":   "Consumer Services",
    "CYBR":   "Technology",
    "DAL":    "Consumer Services",
    "DBX":    "Technology",   # Dropbox
    "DDOG":   "Technology",
    "DE":     "Industrial",
    "DELL":   "Technology",
    "DHR":    "Healthcare",
    "DIS":    "Consumer Services",
    "DKNG":   "Consumer Services",
    "DKS":    "Consumer Services",
    "DLR":    "Technology",   # Digital Realty (data center REIT)
    "DLTR":   "Consumer Services",
    "DXCM":   "Healthcare",
    "EA":     "Technology",
    "EBAY":   "Consumer Services",
    "ECL":    "Materials",
    "EDU":    "Consumer Services",
    "EFX":    "Technology",   # Equifax
    "EL":     "Luxury",       # Estée Lauder
    "ELV":    "Healthcare",
    "EMR":    "Industrial",
    "ENB":    "Energy",
    "ENEL":   "Energy",
    "ENI":    "Energy",
    "ENIC":   "Energy",
    "EOG":    "Energy",
    "EPD":    "Energy",
    "EQIX":   "Technology",
    "EQNR":   "Energy",
    "EQT":    "Energy",
    "ETN":    "Industrial",
    "ETSY":   "Consumer Services",
    "EW":     "Healthcare",
    "EXAS":   "Healthcare",
    "F":      "Automobile",
    "FANG":   "Energy",       # Diamondback Energy
    "FAST":   "Industrial",
    "FCX":    "Materials",
    "FDX":    "Industrial",
    "FICO":   "Technology",
    "FIS":    "Finance",
    "FISV":   "Finance",
    "FITB":   "Finance",
    "FLEX":   "Technology",
    "FLUT":   "Consumer Services", # Flutter (gambling)
    "FMC":    "Materials",
    "FSLR":   "Energy",
    "FTNT":   "Technology",
    "FTV":    "Industrial",
    "FUTU":   "Finance",
    "FVRR":   "Technology",
    "GBTC":   "Finance",
    "GD":     "Industrial",
    "GDDY":   "Technology",
    "GE":     "Industrial",
    "GEHC":   "Healthcare",
    "GEN":    "Technology",   # Gen Digital (cybersecurity)
    "GEV":    "Industrial",   # GE Vernova (energy)
    "GILD":   "Healthcare",
    "GIS":    "Consumer Goods",
    "GME":    "Consumer Services",
    "GMED":   "Healthcare",
    "GM":     "Automobile",
    "GOOGL":  "Technology",
    "GPC":    "Consumer Services",
    "GPN":    "Technology",
    "GRMN":   "Technology",
    "GS":     "Finance",
    "GSK":    "Healthcare",
    "GTLB":   "Technology",
    "GWRE":   "Technology",
    "H":      "Consumer Services", # Hyatt
    "HAL":    "Energy",
    "HAS":    "Consumer Goods",
    "HBAN":   "Finance",
    "HCA":    "Healthcare",
    "HD":     "Consumer Services",
    "HIG":    "Finance",
    "HLT":    "Consumer Services",
    "HMC":    "Automobile",   # Honda
    "HON":    "Industrial",
    "HOOD":   "Finance",
    "HPQ":    "Technology",
    "HUM":    "Healthcare",
    "HUBS":   "Technology",
    "IAC":    "Technology",
    "IBKR":   "Finance",
    "IBM":    "Technology",
    "ICE":    "Finance",
    "IDXX":   "Healthcare",
    "IFF":    "Materials",
    "ILMN":   "Healthcare",
    "INCY":   "Healthcare",
    "INFY":   "Technology",
    "ING":    "Finance",
    "INSM":   "Healthcare",
    "INTC":   "Technology",
    "INTU":   "Technology",
    "IONQ":   "Technology",
    "IONS":   "Healthcare",
    "IPGP":   "Technology",
    "IQV":    "Healthcare",
    "IR":     "Industrial",
    "ISRG":   "Healthcare",
    "IT":     "Technology",   # Gartner
    "ITW":    "Industrial",
    "IX":     "Finance",
    "J":      "Industrial",   # Jacobs (engineering)
    "JAZZ":   "Healthcare",
    "JBL":    "Technology",
    "JBLU":   "Consumer Services",
    "JD":     "Consumer Services",
    "JEF":    "Finance",
    "JLL":    "Finance",
    "JNJ":    "Healthcare",
    "JPM":    "Finance",
    "KB":     "Finance",
    "KBR":    "Industrial",
    "KDP":    "Consumer Goods",
    "KEYS":   "Technology",
    "KGC":    "Materials",
    "KHC":    "Consumer Goods",
    "KIM":    "Finance",
    "KKR":    "Finance",
    "KLAC":   "Technology",
    "KMB":    "Consumer Goods",
    "KMI":    "Energy",
    "KO":     "Consumer Goods",
    "KR":     "Consumer Services",
    "KSPI":   "Finance",
    "KSS":    "Consumer Services",
    "L":      "Finance",
    "LDOS":   "Technology",   # Leidos (defense tech)
    "LEA":    "Automobile",   # Lear Corporation
    "LEN":    "Industrial",
    "LH":     "Healthcare",
    "LHX":    "Industrial",   # L3Harris
    "LI":     "Automobile",   # Li Auto
    "LII":    "Industrial",
    "LIN":    "Materials",
    "LLY":    "Healthcare",
    "LMT":    "Industrial",
    "LNG":    "Energy",
    "LOGI":   "Technology",   # Logitech
    "LOW":    "Consumer Services",
    "LRCX":   "Technology",
    "LSCC":   "Technology",
    "LULU":   "Luxury",
    "LUV":    "Consumer Services",
    "LVS":    "Consumer Services",
    "LYFT":   "Consumer Services",
    "LYV":    "Consumer Services",
    "MA":     "Finance",
    "MAR":    "Consumer Services",
    "MARA":   "Finance",
    "MAS":    "Industrial",
    "MAT":    "Consumer Goods",
    "MBG":    "Automobile",   # Mercedes-Benz
    "MCD":    "Consumer Services",
    "MCHP":   "Technology",
    "MCK":    "Healthcare",
    "MCO":    "Finance",
    "MDB":    "Technology",
    "MDLZ":   "Consumer Goods",
    "MDT":    "Healthcare",
    "MELI":   "Technology",
    "MET":    "Finance",
    "META":   "Technology",
    "MGM":    "Consumer Services",
    "MIDD":   "Industrial",
    "MKC":    "Consumer Goods",
    "MKL":    "Finance",
    "MLM":    "Materials",
    "MMC":    "Finance",
    "MNDY":   "Technology",
    "MNST":   "Consumer Goods",
    "MO":     "Consumer Goods",
    "MOS":    "Materials",
    "MPC":    "Energy",
    "MPWR":   "Technology",
    "MRK":    "Healthcare",
    "MRNA":   "Healthcare",
    "MRVL":   "Technology",
    "MS":     "Finance",
    "MSCI":   "Finance",
    "MSFT":   "Technology",
    "MSI":    "Technology",
    "MSTR":   "Finance",
    "MU":     "Technology",
    "MUFG":   "Finance",
    "NCLH":   "Consumer Services",
    "NDAQ":   "Finance",
    "NEE":    "Energy",
    "NEM":    "Materials",
    "NET":    "Technology",
    "NFLX":   "Technology",   # Netflix
    "NIO":    "Automobile",
    "NKE":    "Consumer Goods",
    "NOC":    "Industrial",
    "NOW":    "Technology",   # ServiceNow
    "NRG":    "Energy",
    "NSC":    "Industrial",
    "NTAP":   "Technology",
    "NTES":   "Technology",
    "NTNX":   "Technology",
    "NTR":    "Materials",
    "NTRS":   "Finance",
    "NU":     "Finance",      # Nu Holdings
    "NUE":    "Materials",
    "NVDA":   "Technology",
    "NVO":    "Healthcare",
    "NVS":    "Healthcare",
    "NXPI":   "Technology",
    "O":      "Finance",
    "ODFL":   "Industrial",
    "OKTA":   "Technology",
    "OMC":    "Consumer Services",
    "ON":     "Technology",   # ON Semiconductor
    "ONON":   "Consumer Goods",
    "ORCL":   "Technology",
    "ORLY":   "Consumer Services",
    "OXY":    "Energy",
    "P911":   "Automobile",   # Porsche
    "PANW":   "Technology",
    "PATH":   "Technology",
    "PAYC":   "Technology",
    "PAYX":   "Technology",
    "PDD":    "Consumer Services", # Pinduoduo/Temu
    "PEP":    "Consumer Goods",
    "PFE":    "Healthcare",
    "PFG":    "Finance",
    "PG":     "Consumer Goods",
    "PGR":    "Finance",
    "PH":     "Industrial",   # Parker Hannifin
    "PHM":    "Industrial",
    "PINS":   "Technology",
    "PLD":    "Finance",
    "PLTR":   "Technology",
    "PM":     "Consumer Goods",
    "PNC":    "Finance",
    "POOL":   "Consumer Services",
    "PPG":    "Materials",
    "PRU":    "Finance",
    "PSA":    "Finance",
    "PSX":    "Energy",
    "PTC":    "Technology",
    "PTON":   "Consumer Goods",
    "PVH":    "Luxury",
    "PYPL":   "Finance",
    "QCOM":   "Technology",
    "RACE":   "Luxury",       # Ferrari
    "RBLX":   "Technology",
    "RCL":    "Consumer Services",
    "RDDT":   "Technology",
    "REGN":   "Healthcare",
    "RELX":   "Technology",
    "RF":     "Finance",
    "RIO":    "Materials",
    "RIVN":   "Automobile",
    "RJF":    "Finance",
    "RL":     "Luxury",       # Ralph Lauren
    "RMD":    "Healthcare",
    "ROK":    "Industrial",
    "ROKU":   "Technology",
    "ROP":    "Industrial",
    "ROST":   "Consumer Services",
    "RS":     "Materials",
    "RSG":    "Industrial",
    "RY":     "Finance",
    "RYAAY":  "Consumer Services", # Ryanair
    "S":      "Technology",   # SentinelOne
    "SAP":    "Technology",
    "SBUX":   "Consumer Services",
    "SCHW":   "Finance",
    "SE":     "Technology",   # Sea Limited
    "SEDG":   "Energy",
    "SHEL":   "Energy",
    "SHOP":   "Technology",
    "SHW":    "Materials",
    "SIE":    "Industrial",
    "SLB":    "Energy",
    "SLF":    "Finance",
    "SMCI":   "Technology",
    "SMFG":   "Finance",
    "SNAP":   "Technology",
    "SNOW":   "Technology",
    "SNPS":   "Technology",
    "SNY":    "Healthcare",
    "SO":     "Energy",
    "SOFI":   "Finance",
    "SONY":   "Technology",
    "SPOT":   "Technology",
    "SPG":    "Finance",
    "SPGI":   "Finance",
    "SQM":    "Materials",
    "SRE":    "Energy",
    "STE":    "Healthcare",
    "STLA":   "Automobile",   # Stellantis
    "STLD":   "Materials",
    "STM":    "Technology",
    "STT":    "Finance",
    "STZ":    "Consumer Goods",
    "SWKS":   "Technology",
    "SYF":    "Finance",
    "SYK":    "Healthcare",
    "SYY":    "Consumer Services",
    "T":      "Telecommunication",
    "TAK":    "Healthcare",
    "TAP":    "Consumer Goods",
    "TD":     "Finance",
    "TDG":    "Industrial",
    "TEAM":   "Technology",
    "TEL":    "Technology",
    "TER":    "Technology",
    "TEVA":   "Healthcare",
    "TFC":    "Finance",
    "TGT":    "Consumer Services",
    "THC":    "Healthcare",
    "TJX":    "Consumer Services",
    "TM":     "Automobile",   # Toyota
    "TMO":    "Healthcare",
    "TMUS":   "Telecommunication",
    "TOL":    "Industrial",
    "TPR":    "Luxury",       # Tapestry (Coach, Kate Spade)
    "TRIP":   "Consumer Services",
    "TRV":    "Finance",
    "TSLA":   "Automobile",
    "TSM":    "Technology",
    "TTWO":   "Technology",
    "TWLO":   "Technology",
    "TXN":    "Technology",
    "TYL":    "Technology",
    "U":      "Technology",   # Unity Software
    "UAA":    "Consumer Goods",
    "UAL":    "Consumer Services",
    "UBER":   "Consumer Services",
    "UBS":    "Finance",
    "UNH":    "Healthcare",
    "UNP":    "Industrial",
    "UPS":    "Industrial",
    "URI":    "Industrial",
    "USB":    "Finance",
    "V":      "Finance",
    "VALE":   "Materials",
    "VEEV":   "Technology",   # Veeva Systems
    "VFC":    "Consumer Goods",
    "VICI":   "Finance",
    "VLO":    "Energy",
    "VMC":    "Materials",
    "VOD":    "Telecommunication",
    "VRSK":   "Industrial",
    "VRSN":   "Technology",
    "VRT":    "Industrial",   # Vertiv
    "VRTX":   "Healthcare",
    "VST":    "Energy",
    "VZ":     "Telecommunication",
    "W":      "Consumer Services", # Wayfair
    "WAB":    "Industrial",
    "WAT":    "Healthcare",
    "WB":     "Technology",   # Weibo
    "WBD":    "Consumer Services",
    "WCC":    "Industrial",
    "WDAY":   "Technology",
    "WDC":    "Technology",
    "WEC":    "Energy",
    "WELL":   "Healthcare",   # Welltower (healthcare REIT)
    "WFC":    "Finance",
    "WHR":    "Consumer Goods",
    "WM":     "Industrial",
    "WMB":    "Energy",
    "WMG":    "Consumer Services",
    "WPC":    "Finance",
    "WPM":    "Materials",
    "WRB":    "Finance",
    "WSM":    "Consumer Goods",
    "WTW":    "Finance",
    "WYNN":   "Consumer Services",
    "XOM":    "Energy",
    "XPO":    "Industrial",
    "XPEV":   "Automobile",
    "YUM":    "Consumer Services",
    "YUMC":   "Consumer Services",
    "ZBH":    "Healthcare",
    "ZBRA":   "Technology",
    "ZM":     "Technology",
    "ZS":     "Technology",
    "ZTO":    "Industrial",
    "ZTS":    "Healthcare",
    # ── Less common / international ────────────────────────────────────────
    "AA":     "Materials",
    "AAL":    "Consumer Services",
    "ABBV":   "Healthcare",
    "ABCL":   "Healthcare",
    "ABNB":   "Consumer Services",
    "ABT":    "Healthcare",
    "ACB":    "Consumer Goods",   # Aurora Cannabis
    "ACGL":   "Finance",
    "ACM":    "Industrial",
    "ADM":    "Consumer Goods",
    "ADNT":   "Automobile",
    "ADS":    "Technology",       # ADS (Adidas)
    "AEE":    "Energy",
    "AEM":    "Materials",
    "AEP":    "Energy",
    "AER":    "Industrial",
    "AES":    "Energy",
    "AF":     "Consumer Services",# Air France
    "AFG":    "Finance",
    "AFL":    "Finance",
    "AFRM":   "Finance",
    "AG":     "Materials",        # First Majestic Silver
    "AGCO":   "Industrial",
    "AGI":    "Materials",
    "AGNC":   "Finance",
    "AGNCM":  "Finance",
    "AIG":    "Finance",
    "AIR":    "Automobile",       # Airbus
    "AIZ":    "Finance",
    "AJG":    "Finance",
    "ALB":    "Materials",
    "ALC":    "Healthcare",
    "ALK":    "Consumer Services",
    "ALKS":   "Healthcare",
    "ALL":    "Finance",
    "ALLE":   "Industrial",
    "ALLY":   "Finance",
    "ALSN":   "Industrial",
    "AMC":    "Consumer Services",
    "AME":    "Industrial",
    "AMGN":   "Healthcare",
    "AMH":    "Finance",
    "AMP":    "Finance",
    "AMT":    "Telecommunication",
    "AMX":    "Telecommunication",
    "AN":     "Consumer Services",
    "AON":    "Finance",
    "AOS":    "Industrial",
    "APA":    "Energy",
    "APD":    "Materials",
    "APG":    "Finance",
    "APLS":   "Healthcare",
    "APO":    "Finance",
    "APP":    "Technology",
    "APTV":   "Automobile",
    "ARE":    "Finance",
    "ARMK":   "Consumer Services",
    "ARRY":   "Energy",
    "ARW":    "Technology",
    "AS":     "Finance",          # Ares Capital
    "ASH":    "Materials",
    "ASND":   "Healthcare",
    "ASX":    "Technology",       # ASE Technology
    "ATI":    "Materials",
    "ATO":    "Energy",
    "ATR":    "Industrial",
    "AU":     "Materials",        # AngloGold
    "AVB":    "Finance",
    "AVNT":   "Materials",
    "AVT":    "Technology",
    "AVTR":   "Healthcare",
    "AVY":    "Industrial",
    "AWK":    "Energy",           # American Water Works
    "AYI":    "Industrial",
    "B":      "Industrial",       # Barnes Group
    "BA":     "Industrial",
    "BAH":    "Industrial",
    "BALL":   "Industrial",
    "BAM":    "Finance",
    "BAP":    "Finance",
    "BAS":    "Materials",        # BASF
    "BAX":    "Healthcare",
    "BAYN":   "Healthcare",       # Bayer
    "BCPE":   "Finance",
    "BCH":    "Finance",
    "BEN":    "Finance",
    "BEP":    "Energy",
    "BEPC":   "Energy",
    "BFAM":   "Consumer Services",
    "BG":     "Consumer Goods",
    "BHC":    "Healthcare",
    "BHP":    "Materials",
    "BIP":    "Industrial",
    "BIRK":   "Luxury",           # Birkenstock
    "BJ":     "Consumer Services",
    "BLD":    "Industrial",
    "BLDR":   "Industrial",
    "BMW":    "Automobile",
    "BN":     "Finance",
    "BMO":    "Finance",
    "BMRN":   "Healthcare",
    "BNP":    "Finance",          # BNP Paribas
    "BNS":    "Finance",
    "BNT":    "Finance",
    "BOKF":   "Finance",
    "BPOP":   "Finance",
    "BRO":    "Finance",
    "BSAC":   "Finance",
    "BUD":    "Consumer Goods",
    "BURL":   "Consumer Services",
    "BWA":    "Automobile",
    "BWXT":   "Industrial",
    "BXP":    "Finance",
    "CAG":    "Consumer Goods",
    "CAH":    "Healthcare",
    "CARR":   "Industrial",
    "CASY":   "Consumer Services",
    "CBSH":   "Finance",
    "CCEP":   "Consumer Goods",
    "CCI":    "Telecommunication",
    "CCJ":    "Energy",
    "CCK":    "Industrial",
    "CCL":    "Consumer Services",
    "CE":     "Materials",
    "CERS":   "Healthcare",
    "CERT":   "Healthcare",
    "CFR":    "Finance",
    "CGC":    "Consumer Goods",
    "CGNX":   "Technology",
    "CHD":    "Consumer Goods",
    "CHRW":   "Industrial",
    "CHT":    "Telecommunication",
    "CHWY":   "Consumer Services",
    "CHYM":   "Healthcare",
    "CIB":    "Finance",
    "CLF":    "Materials",
    "CMS":    "Energy",
    "CNA":    "Finance",
    "CP":     "Industrial",
    "CPA":    "Consumer Services",
    "CPB":    "Consumer Goods",
    "CPT":    "Finance",
    "CQP":    "Energy",
    "CR":     "Industrial",
    "CRBG":   "Finance",
    "CRCL":   "Technology",
    "CRDO":   "Technology",
    "CRH":    "Materials",
    "CRI":    "Consumer Goods",
    "CRON":   "Consumer Goods",
    "CRS":    "Materials",
    "CRSR":   "Technology",
    "CRUS":   "Technology",
    "CRWV":   "Technology",
    "CWBC":   "Finance",
    "CX":     "Materials",        # Cemex
    "CXM":    "Technology",
    "CZR":    "Consumer Services",
    "D":      "Energy",
    "DBK":    "Finance",
    "DCI":    "Industrial",
    "DECK":   "Consumer Goods",
    "DEI":    "Finance",
    "DEO":    "Consumer Goods",   # Diageo
    "DGX":    "Healthcare",
    "DHI":    "Industrial",
    "DJT":    "Consumer Services",
    "DLB":    "Technology",       # Dolby
    "DLTR":   "Consumer Services",
    "DNLI":   "Healthcare",
    "DOC":    "Healthcare",
    "DOCS":   "Healthcare",
    "DOCU":   "Technology",
    "DOV":    "Industrial",
    "DOW":    "Materials",
    "DOX":    "Technology",       # Amdocs
    "DPZ":    "Consumer Services",
    "DRI":    "Consumer Services",
    "DT":     "Technology",       # Dynatrace
    "DTE":    "Energy",
    "DTM":    "Energy",
    "DUK":    "Energy",
    "DUOL":   "Technology",
    "DVA":    "Healthcare",
    "DVN":    "Energy",
    "EC":     "Energy",
    "ED":     "Energy",
    "EG":     "Finance",
    "EGP":    "Finance",
    "EHC":    "Healthcare",
    "EIX":    "Energy",
    "ELAN":   "Healthcare",
    "ELS":    "Finance",
    "EMA":    "Energy",
    "EMBJ":   "Finance",
    "EME":    "Industrial",
    "EMN":    "Materials",
    "ENOV":   "Healthcare",
    "ENR":    "Consumer Goods",   # Energizer
    "ENS":    "Industrial",
    "ENTG":   "Technology",
    "EQH":    "Finance",
    "EQR":    "Finance",
    "ERIE":   "Finance",
    "ESLT":   "Industrial",       # Elbit Systems
    "ESS":    "Finance",
    "ET":     "Energy",
    "ETR":    "Energy",
    "EVR":    "Finance",
    "EVRG":   "Energy",
    "EWBC":   "Finance",
    "EXC":    "Energy",
    "EXE":    "Energy",
    "EXEL":   "Healthcare",
    "EXP":    "Materials",
    "EXPD":   "Industrial",
    "EXPE":   "Consumer Services",
    "EXR":    "Finance",
    "FA":     "Technology",
    "FBIN":   "Consumer Goods",
    "FCNCA":  "Finance",
    "FDS":    "Finance",
    "FE":     "Energy",
    "FER":    "Industrial",
    "FERG":   "Industrial",
    "FFIV":   "Technology",
    "FHN":    "Finance",
    "FIG":    "Finance",
    "FIGS":   "Healthcare",
    "FIX":    "Industrial",
    "FIZZ":   "Consumer Goods",
    "FLG":    "Finance",
    "FLO":    "Consumer Goods",
    "FLS":    "Industrial",
    "FLYW":   "Finance",
    "FMS":    "Healthcare",
    "FMX":    "Consumer Services",
    "FN":     "Technology",
    "FNF":    "Finance",
    "FNV":    "Materials",
    "FOX":    "Consumer Services",
    "FOXF":   "Consumer Services",
    "FRMI":   "Finance",
    "FRT":    "Finance",
    "FSLY":   "Technology",
    "FTAI":   "Industrial",
    "FTS":    "Energy",
    "G":      "Finance",
    "GAP":    "Consumer Goods",
    "GD":     "Industrial",
    "GFL":    "Industrial",
    "GFS":    "Technology",
    "GGG":    "Industrial",
    "GH":     "Healthcare",
    "GIB":    "Technology",
    "GIL":    "Consumer Goods",
    "GLPI":   "Finance",
    "GLW":    "Technology",
    "GLXY":   "Finance",
    "GMAB":   "Healthcare",
    "GNTX":   "Automobile",
    "GO":     "Consumer Services",
    "GOOS":   "Luxury",           # Canada Goose
    "GPK":    "Materials",
    "GWW":    "Industrial",
    "HALO":   "Healthcare",
    "HD":     "Consumer Services",
    "HEI":    "Industrial",
    "HII":    "Industrial",
    "HIMS":   "Healthcare",
    "HLF":    "Consumer Goods",
    "HLI":    "Finance",
    "HMY":    "Materials",
    "HOG":    "Consumer Goods",   # Harley-Davidson
    "HOLX":   "Healthcare",
    "HSIC":   "Healthcare",
    "HST":    "Finance",
    "HSY":    "Consumer Goods",
    "HTGC":   "Finance",
    "HTHT":   "Consumer Services",
    "HUBB":   "Industrial",
    "HUN":    "Materials",
    "HUT":    "Finance",
    "HUYA":   "Technology",
    "HWM":    "Industrial",
    "HXL":    "Materials",
    "IBN":    "Finance",
    "ICLR":   "Healthcare",
    "IEX":    "Industrial",
    "IHG":    "Consumer Services",
    "IMO":    "Energy",
    "INGR":   "Consumer Goods",
    "IOT":    "Technology",
    "IP":     "Materials",
    "IREN":   "Finance",          # crypto mining
    "IRM":    "Technology",       # Iron Mountain
    "ITT":    "Industrial",
    "IVZ":    "Finance",
    "JBHT":   "Industrial",
    "JOBY":   "Consumer Services",# air taxi
    "JUVE":   "Consumer Services",# Juventus
    "KC":     "Technology",       # Kingsoft Cloud
    "KEP":    "Energy",
    "KEX":    "Industrial",
    "KEY":    "Finance",
    "KMT":    "Industrial",
    "KMX":    "Consumer Services",
    "KNX":    "Industrial",
    "KRC":    "Finance",
    "KTOS":   "Industrial",
    "KVUE":   "Consumer Goods",
    "LAMR":   "Consumer Services",
    "LAUR":   "Consumer Services",
    "LAZ":    "Finance",
    "LBTYA":  "Telecommunication",
    "LCID":   "Automobile",
    "LECO":   "Industrial",
    "LEG":    "Industrial",
    "LEVI":   "Consumer Goods",
    "LFUS":   "Technology",
    "LMT":    "Industrial",
    "LNC":    "Finance",
    "LNT":    "Energy",
    "LPLA":   "Finance",
    "LPX":    "Materials",
    "LYB":    "Materials",
    "LZ":     "Consumer Services",
    "M":      "Consumer Services",
    "MAA":    "Finance",
    "MAN":    "Industrial",
    "MASI":   "Healthcare",
    "MBLY":   "Technology",       # Mobileye
    "MFC":    "Finance",
    "MGA":    "Automobile",
    "MHK":    "Consumer Goods",
    "MLCO":   "Consumer Services",
    "MLI":    "Industrial",
    "MMSI":   "Healthcare",
    "MMYT":   "Consumer Services",
    "MOS":    "Materials",
    "MP":     "Materials",
    "MPLX":   "Energy",
    "MRCY":   "Industrial",
    "MS":     "Finance",
    "MSGS":   "Consumer Services",
    "MSM":    "Industrial",
    "MT":     "Materials",
    "MTB":    "Finance",
    "MTCH":   "Technology",
    "MTD":    "Healthcare",
    "MTG":    "Finance",
    "MTSI":   "Technology",
    "MTZ":    "Industrial",
    "NBIX":   "Healthcare",
    "NFG":    "Energy",
    "NGG":    "Energy",
    "NI":     "Energy",
    "NLY":    "Finance",
    "NOV":    "Energy",
    "NTAP":   "Technology",
    "NVO":    "Healthcare",
    "NVR":    "Industrial",
    "NWT":    "Materials",
    "NVT":    "Industrial",
    "NWG":    "Finance",
    "NWL":    "Consumer Goods",
    "NWSA":   "Consumer Services",
    "NXT":    "Industrial",
    "OC":     "Industrial",
    "OGE":    "Energy",
    "OHI":    "Healthcare",
    "OKE":    "Energy",
    "OKLO":   "Energy",
    "ONC":    "Healthcare",
    "OPEN":   "Finance",
    "ORI":    "Finance",
    "OSK":    "Industrial",
    "OTEX":   "Technology",
    "OTIS":   "Industrial",
    "OVV":    "Energy",
    "OWL":    "Finance",
    "PAA":    "Energy",
    "PAAS":   "Materials",
    "PAGS":   "Finance",
    "PB":     "Finance",
    "PBA":    "Energy",
    "PCAR":   "Industrial",
    "PCG":    "Energy",
    "PCOR":   "Technology",
    "PEG":    "Energy",
    "PENN":   "Consumer Services",
    "PFGC":   "Consumer Services",
    "PHG":    "Healthcare",       # Philips
    "PII":    "Consumer Goods",   # Polaris
    "PKG":    "Materials",
    "PKX":    "Materials",
    "PLNT":   "Consumer Services",
    "PNR":    "Industrial",
    "PODD":   "Healthcare",
    "PPL":    "Energy",
    "PR":     "Energy",
    "PSFE":   "Finance",
    "PSKY":   "Consumer Services",
    "PSNY":   "Automobile",       # Polestar
    "PSTG":   "Technology",
    "PUK":    "Finance",
    "PWR":    "Industrial",
    "Q":      "Technology",       # Quintiles/IQVIA spin?
    "QDEL":   "Healthcare",
    "QGEN":   "Healthcare",
    "QRVO":   "Technology",
    "QS":     "Automobile",       # QuantumScape (battery)
    "QSR":    "Consumer Services",
    "QXO":    "Industrial",
    "RBA":    "Industrial",
    "RBC":    "Finance",
    "RBRK":   "Technology",
    "RCI":    "Telecommunication",
    "RDN":    "Finance",
    "RDY":    "Healthcare",
    "REG":    "Finance",
    "REP":    "Energy",
    "RGA":    "Finance",
    "RGLD":   "Materials",
    "RGTI":   "Technology",
    "RH":     "Luxury",           # Restoration Hardware
    "RHI":    "Industrial",
    "RHM":    "Industrial",       # Rheinmetall
    "RIG":    "Energy",
    "RIOT":   "Finance",          # crypto mining
    "RITM":   "Finance",
    "RKLB":   "Industrial",       # Rocket Lab
    "RKT":    "Finance",
    "RMBS":   "Technology",
    "RNO":    "Automobile",       # Renault
    "RNR":    "Finance",
    "ROIV":   "Healthcare",
    "ROL":    "Consumer Services",
    "RPD":    "Technology",       # Rapid7
    "RPM":    "Materials",
    "RPRX":   "Healthcare",
    "RRX":    "Industrial",
    "RSG":    "Industrial",
    "RTO":    "Consumer Services",
    "RUN":    "Energy",           # Sunrun
    "RVMD":   "Healthcare",
    "RVTY":   "Healthcare",
    "SAIL":   "Technology",
    "SATS":   "Telecommunication",
    "SBAC":   "Telecommunication",
    "SBRA":   "Healthcare",
    "SBS":    "Energy",
    "SBSW":   "Materials",
    "SCCO":   "Materials",
    "SCI":    "Consumer Services",
    "SDGR":   "Technology",
    "SEE":    "Materials",
    "SEIC":   "Finance",
    "SF":     "Finance",
    "SGI":    "Technology",
    "SHAK":   "Consumer Services",
    "SHC":    "Healthcare",
    "SHG":    "Finance",
    "SJM":    "Consumer Goods",
    "SLAB":   "Technology",
    "SLG":    "Finance",
    "SLGN":   "Materials",
    "SLM":    "Finance",
    "SMG":    "Consumer Goods",
    "SMMT":   "Healthcare",
    "SMR":    "Energy",
    "SN":     "Energy",
    "SNA":    "Industrial",
    "SNDK":   "Technology",
    "SNN":    "Healthcare",
    "SSL":    "Materials",
    "SSNC":   "Finance",
    "STN":    "Industrial",
    "STNE":   "Finance",
    "STRL":   "Industrial",
    "STZ":    "Consumer Goods",
    "SU":     "Energy",
    "SUI":    "Finance",
    "SW":     "Materials",
    "SWK":    "Industrial",
    "SYM":    "Technology",
    "TAL":    "Consumer Services",
    "TAP":    "Consumer Goods",
    "TCOM":   "Consumer Services",
    "TDY":    "Technology",
    "TECK":   "Materials",
    "TEM":    "Healthcare",
    "TEVA":   "Healthcare",
    "TFX":    "Healthcare",
    "TGTX":   "Healthcare",
    "THO":    "Consumer Goods",
    "TIMB":   "Materials",
    "TKO":    "Consumer Services",
    "TLK":    "Telecommunication",
    "TLN":    "Energy",
    "TLRY":   "Consumer Goods",
    "TME":    "Technology",
    "TN":     "Industrial",
    "TNL":    "Consumer Services",
    "TOST":   "Technology",
    "TPG":    "Finance",
    "TPL":    "Energy",
    "TRGP":   "Energy",
    "TRI":    "Finance",
    "TRMB":   "Technology",
    "TRN":    "Industrial",
    "TROW":   "Finance",
    "TRP":    "Energy",
    "TRU":    "Finance",
    "TS":     "Materials",
    "TSCO":   "Consumer Services",
    "TSEM":   "Technology",
    "TSN":    "Consumer Goods",
    "TT":     "Industrial",
    "TTC":    "Industrial",
    "TTD":    "Technology",
    "TU":     "Telecommunication",
    "TUI":    "Consumer Services",
    "TW":     "Finance",
    "TXT":    "Industrial",
    "UAA":    "Consumer Goods",
    "UDR":    "Finance",
    "UGI":    "Energy",
    "UHS":    "Healthcare",
    "UI":     "Technology",       # Ubiquiti
    "UL":     "Consumer Goods",
    "ULS":    "Finance",
    "ULTA":   "Consumer Services",
    "UNM":    "Finance",
    "USB":    "Finance",
    "USFD":   "Consumer Services",
    "UTHR":   "Healthcare",
    "VC":     "Automobile",
    "VCYT":   "Healthcare",
    "VFS":    "Automobile",       # VinFast
    "VIK":    "Consumer Services",
    "VIRT":   "Finance",
    "VIV":    "Telecommunication",
    "VLTO":   "Technology",
    "VMI":    "Industrial",
    "VNO":    "Finance",
    "VNOM":   "Energy",
    "VRSK":   "Industrial",
    "VTR":    "Healthcare",
    "VTRS":   "Healthcare",
    "VYX":    "Technology",
    "WAT":    "Healthcare",
    "WBS":    "Finance",
    "WCN":    "Industrial",
    "WDS":    "Energy",
    "WEN":    "Consumer Services",
    "WES":    "Energy",
    "WEX":    "Finance",
    "WF":     "Finance",
    "WLK":    "Materials",
    "WMB":    "Energy",
    "WMS":    "Industrial",
    "WSO":    "Industrial",
    "WST":    "Healthcare",
    "WTRG":   "Energy",
    "WU":     "Finance",
    "WWD":    "Industrial",
    "WY":     "Materials",
    "XEL":    "Energy",
    "XP":     "Finance",
    "XRAY":   "Healthcare",
    "XYL":    "Industrial",
    "XYZ":    "Technology",
    "YMM":    "Consumer Services",
    "YPF":    "Energy",
    "ZD":     "Technology",
    "ZETA":   "Technology",
    "ZION":   "Finance",
    "ZYME":   "Healthcare",
}
